blank_issues_enabled: false
contact_links:
  - name: Instana Support Portal
    url: https://support.instana.com
    about: Please ask questions related to your installation there.
  - name: Feature Requests
￼    url: https://automation-management.ideas.ibm.com/?project=INSTANA
￼    about: Please file feature requests there (or search for existing requests and vote for them). Do not use Github issues for feature requests.
