# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import tests.apps.grpc_server.stan_pb2 as stan__pb2


class StanStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SayHello = channel.unary_unary(
        '/stan.Stan/SayHello',
        request_serializer=stan__pb2.IncomingMessage.SerializeToString,
        response_deserializer=stan__pb2.OutgoingMessage.FromString,
        )


class StanServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SayHello(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_StanServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SayHello': grpc.unary_unary_rpc_method_handler(
          servicer.SayHello,
          request_deserializer=stan__pb2.IncomingMessage.FromString,
          response_serializer=stan__pb2.OutgoingMessage.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'stan.Stan', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
