apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: python-tracer-ci-pipeline
spec:
  params:
  - name: revision
    type: string
  workspaces:
    - name: python-tracer-ci-pipeline-pvc
  tasks:
    - name: clone
      params:
      - name: revision
        value: $(params.revision)
      taskRef:
        name: python-tracer-clone-task
      workspaces:
        - name: task-pvc
          workspace: python-tracer-ci-pipeline-pvc
    - name: unittest-default
      displayName: "Platforms and Browsers: $(params.platform) and $(params.browser)"
      runAfter:
        - clone
      matrix:
        params:
          - name: imageDigest
            value:
              # public.ecr.aws/docker/library/python:3.8.20-bookworm
              - "sha256:7aa279fb41dad2962d3c915aa6f6615134baa412ab5aafa9d4384dcaaa0af15d"
              # public.ecr.aws/docker/library/python:3.9.20-bookworm
              - "sha256:54b70fa5a9a48299b6c8b47e3c1a0b969271f9769810f1ab17547f1fecdd72cc"
              # public.ecr.aws/docker/library/python:3.10.15-bookworm
              - "sha256:2eb72484c25c39aba019b0ab5679c2436833a0b705e955ed8e13c06ee900dd63"
              # public.ecr.aws/docker/library/python:3.11.10-bookworm
              - "sha256:15f10b142547000e2429615b3d314474ae7d6ac062a8dd2c9246adcee7068e55"
              # public.ecr.aws/docker/library/python:3.12.7-bookworm
              - "sha256:4429a1580a1db32addb5127499a88a8bc6eecb08c7ea19a77b5b69c32f840acd"
              # public.ecr.aws/docker/library/python:3.13.0-bookworm
              - "sha256:ecd27b6c43d8d84b0058e7db4aaa06a1bfe970d0fb9bb7cf39f9536850f71510"
      taskRef:
        name: python-tracer-unittest-default-task
      workspaces:
        - name: task-pvc
          workspace: python-tracer-ci-pipeline-pvc
    - name: unittest-cassandra
      runAfter:
        - clone
      matrix:
        params:
          - name: imageDigest
            value:
              # public.ecr.aws/docker/library/python:3.9.20-bookworm
              - "sha256:54b70fa5a9a48299b6c8b47e3c1a0b969271f9769810f1ab17547f1fecdd72cc"
      taskRef:
        name: python-tracer-unittest-cassandra-task
      workspaces:
        - name: task-pvc
          workspace: python-tracer-ci-pipeline-pvc
    - name: unittest-gevent-starlette
      runAfter:
        - clone
      matrix:
        params:
          - name: imageDigest
            value:
              # public.ecr.aws/docker/library/python:3.9.20-bookworm
              - "sha256:54b70fa5a9a48299b6c8b47e3c1a0b969271f9769810f1ab17547f1fecdd72cc"
      taskRef:
        name: python-tracer-unittest-gevent-starlette-task
      workspaces:
        - name: task-pvc
          workspace: python-tracer-ci-pipeline-pvc
    - name: unittest-aws
      runAfter:
        - clone
      matrix:
        params:
          - name: imageDigest
            value:
              # public.ecr.aws/docker/library/python:3.12.7-bookworm
              - "sha256:4429a1580a1db32addb5127499a88a8bc6eecb08c7ea19a77b5b69c32f840acd"
      taskRef:
        name: python-tracer-unittest-aws-task
      workspaces:
        - name: task-pvc
          workspace: python-tracer-ci-pipeline-pvc
