apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: python-tracer-ci-pipeline
spec:
  params:
  - name: revision
    type: string
  - name: py-versions
    type: array
    default:
      - "3.8"
      - "3.9"
      - "3.10"
      - "3.11"
      - "3.12"
      - "3.13"
  - name: py-version-latest
    type: string
    default: "3.13"
  - name: py-version-next
    type: string
    default: "3.14.0rc2"
  workspaces:
    - name: python-tracer-ci-pipeline-pvc
  tasks:
    - name: clone
      params:
      - name: revision
        value: $(params.revision)
      taskRef:
        name: python-tracer-clone-task
      workspaces:
        - name: task-pvc
          workspace: python-tracer-ci-pipeline-pvc
    - name: unittest-py-version
      displayName: "Unittest for Python $(params.py-version)"
      runAfter:
        - clone
      matrix:
        params:
          - name: py-version
            value: $(params.py-versions)
      taskRef:
        name: python-tracer-unittest-py-version-task
      workspaces:
        - name: task-pvc
          workspace: python-tracer-ci-pipeline-pvc
    - name: unittest-cassandra
      displayName: "Unittest for Cassandra with Python $(params.py-version)"
      runAfter:
        - clone
      matrix:
        params:
          - name: py-version
            value:
              - $(params.py-version-latest)
      taskRef:
        name: python-tracer-unittest-cassandra-task
      workspaces:
        - name: task-pvc
          workspace: python-tracer-ci-pipeline-pvc
    - name: unittest-gevent-starlette
      displayName: "Unittest for Gevent and Starlette with Python $(params.py-version)"
      runAfter:
        - clone
      matrix:
        params:
          - name: py-version
            value:
              - $(params.py-version-latest)
      taskRef:
        name: python-tracer-unittest-gevent-starlette-task
      workspaces:
        - name: task-pvc
          workspace: python-tracer-ci-pipeline-pvc
    - name: unittest-aws
      displayName: "Unittest for AWS with Python $(params.py-version)"
      runAfter:
        - clone
      matrix:
        params:
          - name: py-version
            value:
              - $(params.py-version-latest)
      taskRef:
        name: python-tracer-unittest-aws-task
      workspaces:
        - name: task-pvc
          workspace: python-tracer-ci-pipeline-pvc
    - name: unittest-kafka
      displayName: "Unittest for Kafka with Python $(params.py-version)"
      runAfter:
        - clone
      matrix:
        params:
          - name: py-version
            value:
              - $(params.py-version-latest)
      taskRef:
        name: python-tracer-unittest-kafka-task
      workspaces:
        - name: task-pvc
          workspace: python-tracer-ci-pipeline-pvc
    - name: unittest-python-next
      displayName: "Unittest for next Python $(params.py-version)"
      runAfter:
        - clone
      matrix:
        params:
          - name: py-version
            value:
              - $(params.py-version-next)
      taskRef:
        name: python-tracer-unittest-python-next-task
      workspaces:
        - name: task-pvc
          workspace: python-tracer-ci-pipeline-pvc
