apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: python-tracer-ci-pipeline
spec:
  params:
  - name: revision
    type: string
  workspaces:
    - name: python-tracer-ci-pipeline-pvc
  tasks:
    - name: clone
      params:
      - name: revision
        value: $(params.revision)
      taskRef:
        name: python-tracer-clone-task
      workspaces:
        - name: task-pvc
          workspace: python-tracer-ci-pipeline-pvc
    - name: unittest-default
      runAfter:
        - clone
      matrix:
        params:
          - name: imageDigest
            value:
              # 3.8.20-bookworm
              - "sha256:f53fd710218c3c5415229037afaf04d0f32acba87dd90d48863fbdab4227ac89"
              # 3.9.20-bookworm
              - "sha256:dbb0be5b67aa84b9e3e4f325c7844ab439f40a5cca717c5b24e671cfb41dbb46"
              # 3.10.15-bookworm
              - "sha256:b346d9d55e40cd6079db55370581b3bd24067acf5f1acc386107ec0843102ec9"
              # 3.11.10-bookworm
              - "sha256:3cd9b520be95c671135ea1318f32be6912876024ee16d0f472669d3878801651"
              # 3.12.6-bookworm
              - "sha256:af6fa5c329d6bd6dec52855ccb8bb37c30fb8f00819953a035d49499e43b2c9b"
              # 3.13.0rc2-bookworm
              - "sha256:3aed70fd4585395e47c6005f0082b966151561f3c4070a3ed9d2fb594bbf44b8"
      taskRef:
        name: python-tracer-unittest-default-task
      workspaces:
        - name: task-pvc
          workspace: python-tracer-ci-pipeline-pvc
    - name: unittest-cassandra
      runAfter:
        - clone
      matrix:
        params:
          - name: imageDigest
            value:
              # 3.9.20-bookworm
              - "sha256:dbb0be5b67aa84b9e3e4f325c7844ab439f40a5cca717c5b24e671cfb41dbb46"
      taskRef:
        name: python-tracer-unittest-cassandra-task
      workspaces:
        - name: task-pvc
          workspace: python-tracer-ci-pipeline-pvc
    - name: unittest-couchbase
      runAfter:
        - clone
      matrix:
        params:
          - name: imageDigest
            value:
              # 3.9.20-bookworm
              - "sha256:dbb0be5b67aa84b9e3e4f325c7844ab439f40a5cca717c5b24e671cfb41dbb46"
      taskRef:
        name: python-tracer-unittest-couchbase-task
      workspaces:
        - name: task-pvc
          workspace: python-tracer-ci-pipeline-pvc
    - name: unittest-gevent-starlette
      runAfter:
        - clone
      matrix:
        params:
          - name: imageDigest
            value:
              # 3.9.20-bookworm
              - "sha256:dbb0be5b67aa84b9e3e4f325c7844ab439f40a5cca717c5b24e671cfb41dbb46"
      taskRef:
        name: python-tracer-unittest-gevent-starlette-task
      workspaces:
        - name: task-pvc
          workspace: python-tracer-ci-pipeline-pvc
    - name: unittest-googlecloud
      runAfter:
        - clone
      matrix:
        params:
          - name: imageDigest
            value:
              # 3.11.10-bookworm
              - "sha256:3cd9b520be95c671135ea1318f32be6912876024ee16d0f472669d3878801651"
              # 3.12.6-bookworm
              - "sha256:af6fa5c329d6bd6dec52855ccb8bb37c30fb8f00819953a035d49499e43b2c9b"
      taskRef:
        name: python-tracer-unittest-googlecloud-task
      workspaces:
        - name: task-pvc
          workspace: python-tracer-ci-pipeline-pvc
    - name: unittest-aws
      runAfter:
        - clone
      matrix:
        params:
          - name: imageDigest
            value:
              # 3.12.6-bookworm
              - "sha256:af6fa5c329d6bd6dec52855ccb8bb37c30fb8f00819953a035d49499e43b2c9b"
      taskRef:
        name: python-tracer-unittest-googlecloud-task
      workspaces:
        - name: task-pvc
          workspace: python-tracer-ci-pipeline-pvc
