apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: python-tracer-ci-pipeline
spec:
  params:
  - name: revision
    type: string
  - name: py-312-imageDigest
    type: string
    default: public.ecr.aws/docker/library/python:3.12-trixie
  - name: py-313-imageDigest
    type: string
    default: public.ecr.aws/docker/library/python:3.13-trixie
  - name: py-314-imageDigest
    type: string
    default: public.ecr.aws/docker/library/python:3.14-trixie
  workspaces:
    - name: python-tracer-ci-pipeline-pvc
  tasks:
    - name: clone
      displayName: "clone $(params.revision)"
      params:
      - name: revision
        value: $(params.revision)
      taskRef:
        name: python-tracer-clone-task
      workspaces:
        - name: task-pvc
          workspace: python-tracer-ci-pipeline-pvc
    - name: unittest-default
      displayName: "Python $(params.imageDigest)"
      runAfter:
        - clone
      matrix:
        params:
          - name: imageDigest
            value:
            - $(params.py-313-imageDigest)
            - $(params.py-314-imageDigest)
      taskRef:
        name: python-tracer-unittest-default-task
      workspaces:
        - name: task-pvc
          workspace: python-tracer-ci-pipeline-pvc
    - name: unittest-cassandra
      runAfter:
        - clone
      params:
        - name: imageDigest
          value: $(params.py-312-imageDigest)
      taskRef:
        name: python-tracer-unittest-cassandra-task
      workspaces:
        - name: task-pvc
          workspace: python-tracer-ci-pipeline-pvc
    - name: unittest-gevent-starlette
      runAfter:
        - clone
      params:
        - name: imageDigest
          value: $(params.py-313-imageDigest)
      taskRef:
        name: python-tracer-unittest-gevent-starlette-task
      workspaces:
        - name: task-pvc
          workspace: python-tracer-ci-pipeline-pvc
    - name: unittest-kafka
      runAfter:
        - clone
      params:
        - name: imageDigest
          value: $(params.py-313-imageDigest)
      taskRef:
        name: python-tracer-unittest-kafka-task
      workspaces:
        - name: task-pvc
          workspace: python-tracer-ci-pipeline-pvc
