apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: python-tracer-prepuller
spec:
  selector:
    matchLabels:
      name: python-tracer-prepuller
  template:
    metadata:
      labels:
        name: python-tracer-prepuller
    spec:
      # Configure an init container for each image you want to pull
      initContainers:
        - name: prepuller-git
          # public.ecr.aws/docker/library/alpine:3.20.3
          image: public.ecr.aws/docker/library/alpine@sha256:029a752048e32e843bd6defe3841186fb8d19a28dae8ec287f433bb9d6d1ad85
          command: ["sh", "-c", "'true'"]
        - name: prepuller-google-cloud-pubsub
          # quay.io/thekevjames/gcloud-pubsub-emulator:501.0.0
          image: quay.io/thekevjames/gcloud-pubsub-emulator@sha256:9bad1f28e6a3d6cd5f462c654c736faa4cf49732d9422ddb427ad30f3037c0ff
          command: ["sh", "-c", "'true'"]
        - name: prepuller-cassandra
          # public.ecr.aws/docker/library/cassandra:3.11.16-jammy
          image: public.ecr.aws/docker/library/cassandra@sha256:b175d99b80f8108594d00c705288fdb3186b9fc07b30b4c292c3592cddb5f0b5
          command: ["sh", "-c", "'true'"]
        - name: prepuller-rabbitmq
          # public.ecr.aws/docker/library/rabbitmq:3.13.0
          image: public.ecr.aws/docker/library/rabbitmq@sha256:39de1a4fc6c72d12bd5dfa23e8576536fd1c0cc8418344cd5a51addfc9a1145d
          command: ["sh", "-c", "'true'"]
        - name: prepuller-redis
          # public.ecr.aws/docker/library/redis:7.2.4-bookworm
          image: public.ecr.aws/docker/library/redis@sha256:9341b6548cc35b64a6de0085555264336e2f570e17ecff20190bf62222f2bd64
          command: ["sh", "-c", "'true'"]
        - name: prepuller-mongo
          # public.ecr.aws/docker/library/mongo:7.0.6
          image: public.ecr.aws/docker/library/mongo@sha256:3a023748ee30e915dd51642f1ef430c73c4e54937060054ca84c70417f510cc5
          command: ["sh", "-c", "'true'"]
        - name: prepuller-mariadb
          # public.ecr.aws/docker/library/mariadb:11.3.2
          image: public.ecr.aws/docker/library/mariadb@sha256:a4a81ab6d190db84b67f286fd0511cdea619a24b63790b3db4fb69d263a5cd37
          command: ["sh", "-c", "'true'"]
        - name: prepuller-postgres
          # public.ecr.aws/docker/library/postgres:16.2-bookworm
          image: public.ecr.aws/docker/library/postgres@sha256:07572430dbcd821f9f978899c3ab3a727f5029be9298a41662e1b5404d5b73e0
          command: ["sh", "-c", "'true'"]
        - name: prepuller-38
          # public.ecr.aws/docker/library/python:3.8.20-bookworm
          image: public.ecr.aws/docker/library/python@
          command: ["sh", "-c", "'true'"]
        - name: prepuller-39
          # public.ecr.aws/docker/library/python:3.9.21-bookworm
          image: public.ecr.aws/docker/library/python@sha256:dd8b65c39a729f946398d2e03a3e6defc8c0cfec409b9f536200634ad6408b54
          command: ["sh", "-c", "'true'"]
        - name: prepuller-310
          # public.ecr.aws/docker/library/python:3.10.16-bookworm
          image: public.ecr.aws/docker/library/python@sha256:3ba2e48b887586835af6a0c35fc6fc6086fb4881e963082330ab0a35f3f42c16
          command: ["sh", "-c", "'true'"]
        - name: prepuller-311
          # public.ecr.aws/docker/library/python:3.11.11-bookworm
          image: public.ecr.aws/docker/library/python@sha256:2c80c66d876952e04fa74113864903198b7cfb36b839acb7a8fef82e94ed067c
          command: ["sh", "-c", "'true'"]
        - name: prepuller-312
          # public.ecr.aws/docker/library/python:3.12.8-bookworm
          image: public.ecr.aws/docker/library/python@sha256:0fc7e6322b146c3fb01782d61412921b08f06439682105bc4e5c7f2dbfc56371
          command: ["sh", "-c", "'true'"]
        - name: prepuller-313
          # public.ecr.aws/docker/library/python:3.13.1-bookworm
          image: public.ecr.aws/docker/library/python@sha256:3b1b63f17c5197411ee572be110333dae4b9d6f2fbc4f84c790f644e791d356b
          command: ["sh", "-c", "'true'"]
        - name: prepuller-314
          # public.ecr.aws/docker/library/python:3.14.0a2-bookworm
          image: public.ecr.aws/docker/library/python@sha256:67eabdadd211c2768dbe0b4f311b27f889b755a6cb93392f41c8773c15affd67
          command: ["sh", "-c", "'true'"]

      # Use the pause container to ensure the Pod goes into a `Running` phase
      # but doesn't take up resource on the cluster
      containers:
        - name: pause
          image: gcr.io/google_containers/pause:3.2
          resources:
            limits:
              cpu: 1m
              memory: 8Mi
            requests:
              cpu: 1m
              memory: 8Mi
