name: Test Python future version

on:
  workflow_dispatch:        # Manual trigger.
  schedule:
    - cron: '3 1 * * 1-5'   # Every Monday to Friday at 03:01 AM.
  push:
    branches:
      - main
      - python3150_ghaction

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/pvital/pvital-python:latest
    steps:
      - uses: actions/checkout@v5
      #- name: Set up Python 3.15.0
      #  uses: actions/setup-python@v5
      #  with:
      #    python-version: 3.15.0-alpha.7
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      #- name: Install Python test dependencies
      #  run: |
      #     pip install -r tests/requirements-pre315.txt
      - name: Test with pytest
        run: |
          pytest -v --doctest-modules --junitxml=junit/test-results.xml tests


