apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: python-currency-pipelinerun
spec:
  params:
  - name: revision
    value: "main"
  pipelineRef:
    name: python-currency-pipeline
  serviceAccountName: currency-serviceaccount
  workspaces:
  - name: currency-pvc
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi
