apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: python-currency-cron-listener
spec:
  serviceAccountName: tekton-triggers-eventlistener-serviceaccount
  triggers:
    - name: currency-cron-trigger
      template:
        ref: python-currency-trigger-template
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: python-currency-trigger-template
spec:
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: python-currency-
    spec:
      pipelineRef:
        name: python-currency-pipeline
      serviceAccountName: currency-serviceaccount
      params:
      - name: revision
        value: "main"
      workspaces:
      - name: currency-pvc
        volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 100Mi
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: python-currency-cronjob
spec:
  schedule: "35 0 * * Mon-Fri"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: http-request-to-el-svc
            image: quay.io/curl/curl:latest
            imagePullPolicy: IfNotPresent
            args: ["curl", "-X", "POST", "--data", "{}", "el-python-currency-cron-listener.default.svc.cluster.local:8080"]
          restartPolicy: OnFailure
---
