apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone-task
spec:
  params:
  - name: revision
    type: string
  workspaces:
    - name: task-pvc
      mountPath: /workspace
  steps:
    - name: clone-repo
      # public.ecr.aws/docker/library/alpine:3.20.3
      image: public.ecr.aws/docker/library/alpine@sha256:029a752048e32e843bd6defe3841186fb8d19a28dae8ec287f433bb9d6d1ad85
      script: |
        #!/bin/sh
        echo "Installing git"
        apk fix && apk --no-cache --update add git gpg less openssh patch
        echo "Cloning repo"
        cd /workspace && git clone --filter=blob:none --sparse --depth 1 https://github.com/instana/python-sensor -b $(params.revision)
        cd python-sensor
        git sparse-checkout add .tekton/.currency
        ls -lah /workspace/python-sensor
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: generate-currency-report-task
spec:
  workspaces:
    - name: task-pvc
      mountPath: /workspace
  steps:
    - name: generate-currency-report
      # public.ecr.aws/docker/library/python:3.12.11-bookworm
      image: public.ecr.aws/docker/library/python@sha256:01b17a5e297dd60629347a17d7c27908fc2c049e81a8cea3d5a1141f38777b8f
      script: |
        #!/usr/bin/env bash
        cd /workspace/python-sensor/.tekton/.currency

        python -m venv /tmp/venv
        source /tmp/venv/bin/activate
        pip install -r resources/requirements.txt

        python scripts/generate_report.py
        if [ $? -ne 0 ]; then
            echo "Error occurred while generating the python tracer currency report." >&2
            exit 1
        fi
        cat docs/report.md
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: upload-currency-report-task
spec:
  params:
    - name: github-token-secret
      default: instanacd-github-api-token
  workspaces:
    - name: task-pvc
      mountPath: /workspace
  steps:
    - name: upload-currency-report
      # public.ecr.aws/docker/library/alpine:3.20.3
      image: public.ecr.aws/docker/library/alpine@sha256:029a752048e32e843bd6defe3841186fb8d19a28dae8ec287f433bb9d6d1ad85
      env:
        - name: GH_ENTERPRISE_TOKEN
          valueFrom:
            secretKeyRef:
              name: $(params.github-token-secret)
              key: "GH_ENTERPRISE_TOKEN"
      script: |
        #!/bin/sh
        echo "Installing git"
        apk fix && apk --no-cache --update add git gpg less openssh patch

        echo "Cloning repo"
        cd /workspace        
        git clone https://oauth2:$GH_ENTERPRISE_TOKEN@github.ibm.com/instana/tracer-reports.git

        if [ $? -ne 0 ]; then
            echo "The attempt to clone the tracer-reports repository failed, preventing the upload of python tracer currency report." >&2
            exit 1
        fi
        
        cd tracer-reports

        cp ../python-sensor/.tekton/.currency/docs/report.md ./automated/currency/python/report.md

        git config user.name "Instanacd PAT for GitHub Enterprise"
        git config user.email instana.ibm.github.enterprise@ibm.com
        
        git add .
        
        git commit -m "chore: Updated Python currency report"
        git push origin main
